api/urls.py
from django.urls import path
from . import views 


app_name = 'api'
urlpatterns = [
    path('customers' , views.CustomerList.as_view() , name='customer_list')   ,
    path('sp_request/<int:pk>' , views.SparePartRequestDetails.as_view() , name='sp_request_details')    ,
]

quarter_crm/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('core.urls' ,namespace='core')),
    path('api/' , include('api.urls' ,namespace='api')),
    path('service/' , include('service.urls' ,namespace='service')),
    path('auth/' , include('users.urls' , namespace='users')) , 
    path('quarter/', include('quarter.urls' , namespace='quarter') ) ,
    path('i18n/', include('django.conf.urls.i18n')),
    path('__debug__/', include('debug_toolbar.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from django.urls import path
from . import views


app_name = 'service'
urlpatterns = [
    
    path('' , views.ServiceListView.as_view() , name = 'service_list'),
    path('new' , views.CreateService.as_view() , name = 'add_service'),
    path('<int:pk>/details' , views.ServiceDetails.as_view() , name = 'service_details'),
    path('<int:pk>/delete' , views.DeleteService.as_view() , name='delete_service') ,
    path('update_status' , views.UpdateServiceStatus.as_view() , name='update_service_status') ,
    path('hold_service' , views.HoldService.as_view() , name='hold_service') ,
    path('favourite_service' , views.FavouriteService.as_view() , name='favourite_service'),
    path('set_appointment' , views.SetAppointment.as_view() , name='set_appointment'),
    path('confirm_excution' , views.ConfirmExcution.as_view() , name='confirm_excution'),
    path('spare_part_request' , views.SparePartRequest.as_view() , name='spare_part_request'),
    path('sp/confirm_recieve' , views.ConfirmSparePartRecieve.as_view() , name='confirm_sp_recievce') , 
    path('install' , views.InstallListView.as_view() , name='install'),
    path('repair' , views.RepairListView.as_view() , name='repair'),
    # htmx views 
    path('service_request' , views.service_request , name='service_request'),
    path('get_data' , views.render_service_data , name='get_data')
]

users/urls.py
from django.urls import path
from . import views 
from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('login' , views.Login.as_view() , name='login') ,
    path('logout' ,LogoutView.as_view()  , name='logout'),
    
    path('user/list' , views.UserList.as_view() , name='user_list'),
    path('user/<int:pk>' , views.UserDetails.as_view() , name='user_details'),
    path('user/new' , views.CreateUser.as_view() , name='create_user'),
    path('user/<int:pk>/delete' , views.DeleteUser.as_view() , name='delete_user'),
    path('user/edit'  , views.EditUserDetails.as_view() , name='edit_user_details'),
    path('user/change_password' , views.ChangeUserPassword.as_view() , name='change_password'),
    
    # validate username 
    path('validate_username' , views.validate_username , name='validate_username')
]

core/models.py
from django.db import models
from django.conf import settings


# Create your models here.
User = settings.AUTH_USER_MODEL

class Customer(models.Model):
    name = models.CharField(max_length=255 ) 
    phone_number = models.CharField(max_length= 15 , unique = True )
    address = models.CharField(max_length= 255 , blank=True)
    city = models.CharField(max_length=50 , blank=True)
    created_by = models.ForeignKey(User , on_delete=models.SET_NULL , null =True , blank = True )
    created_at = models.DateTimeField(auto_now_add=True)
    
    
    def __str__(self):
        return self.name
    

class LateDays(models.Model):
    days = models.PositiveIntegerField(default=3)
    
    class Meta:
        verbose_name_plural = 'Late Days'
    
    def __str__(self):
        return f'late days are {self.days}'

service/models.py
from django.db import models
from .choices import SERVICE_TYPE, CUSTOMER_TYPE, REQUEST_STATUS, SPARE_PART_STATUS
from core.models import Customer
from django.conf import settings
import random
from .utils import generate_ref_number
from datetime import timedelta, date
from django.utils import timezone
from django.db.models import Case, When
from .managers import ServiceManager, AppointmentManager
from core.models import LateDays
import uuid
import os 
# Create your models here.
    
def get_file_path(instance, filename):
    """Generate a unique filename for the uploaded file."""
    ext = filename.split('.')[-1]
    filename = f"{uuid.uuid4()}.{ext}"
    return os.path.join('files/', filename)



User = settings.AUTH_USER_MODEL

status_ordering = Case(
    When(status='new', then=0),
    When(status='under_process', then=1),
    When(status='done', then=2),
    When(status='completed', then=3),
    output_field=models.IntegerField(),
)



class Service(models.Model):
    ref_number = models.CharField(max_length=15, blank=True, null=True)
    customer = models.CharField(max_length=255  , null = True , blank=True )
    phone_number = models.CharField(max_length=255 , null = True , blank=True )
    address = models.CharField(max_length=255, blank=True, null=True)
    customer_type = models.CharField(
        max_length=15, choices=CUSTOMER_TYPE, default='cash')
    service_type = models.CharField(max_length=10, choices=SERVICE_TYPE)
    machine_type = models.CharField(max_length=100, blank=True, null=True)
    invoice_number = models.CharField(max_length=30, blank=True, null=True)
    status = models.CharField(
        max_length=15, choices=REQUEST_STATUS, default='new')
    notes = models.CharField(max_length=255, blank=True, null=True)
    company = models.ForeignKey(User, on_delete=models.SET_NULL,
                                null=True, blank=True, related_name='warranty_company')
    ac_count = models.PositiveIntegerField(default= 0, blank=True , null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    last_update = models.DateTimeField(auto_now=True)
    code = models.CharField(unique=True, max_length=12,
                            blank=True, null=True, editable=False)
    favourite = models.BooleanField(default=False)
    hold = models.BooleanField(default=False)
    archive = models.BooleanField(default=False)

    objects = ServiceManager()

    def __str__(self):
        return self.ref_number

    def save(self, *args, **kwargs):
        if not self.code:
            while True:
                code = str(random.randint(1000, 9999))
                if not Service.objects.filter(code=code , archive = False).exists():
                    self.code = code
                    break
        if not self.ref_number:
            self.ref_number = generate_ref_number(self.service_type)
        super().save(*args, **kwargs)

    @property
    def late(self):
        '''
        Return True if order is late 
        late order has passed --latedays settings default == 3 -- and status is still new 
        '''
        days = LateDays.objects.last().days
        three_days_ago = timezone.now() - timedelta(days=days - 1)
        return self.status == 'new' and self.created_at <= three_days_ago and self.hold == False

    def has_open_sp_requests(self):
        '''
        Checks if service has unrecieved spare parts requests 
        '''
        return self.sp_request.filter(status='pending').exists()


class File(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    file = models.FileField(upload_to=get_file_path)
    cretaed_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self) -> str:
        return 'Service File '


class Appointment(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    technician = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True, related_name='appointment_tech')
    date = models.DateField()
    notes = models.CharField(max_length=300, blank=True, null=True)
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    objects = AppointmentManager()

    def __str__(self):
        return f'{self.service} Appointment !'

    @property
    def today(self):
        today = date.today()
        return self.date == today


class ExcutionFile(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    file = models.FileField(upload_to=get_file_path)
    cretaed_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.service} exec file . '


class HoldReason(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    reason = models.TextField(max_length=300, blank=True, null=True)
    details = models.TextField(max_length=300 , blank = True , null = True )
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    canceled_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True, related_name='hold_canceled_by')
    canceled_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f'{self.service} Hold Reason !'


class HoldFile(models.Model):
    hold_reason = models.ForeignKey(HoldReason, on_delete=models.CASCADE)
    file = models.FileField(upload_to=get_file_path)
    cretaed_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)


# spare parts request :
class SparePartRequest(models.Model):
    service = models.ForeignKey(
        Service, on_delete=models.CASCADE, related_name='sp_request')
    requested_parts = models.CharField(max_length=255, blank=True, null=True)
    details = models.CharField(max_length=300, blank=True, null=True)
    status = models.CharField(
        max_length=15, choices=SPARE_PART_STATUS, default='pending')
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    recievied_at = models.DateTimeField(blank=True , null=True)
    recievied_by = models.ForeignKey(User , on_delete=models.SET_NULL , null=True ,blank=True , related_name='sp_recieved')

    class Meta:
        verbose_name = 'Spare Part Reauest'
        verbose_name_plural = 'Spare Part Reauests'

    def __str__(self):
        return f'{self.service} spare part request .'

repair/forms.py
from django.forms import ModelForm
from .models import Repair_request


class RepairRequestForm(ModelForm):
    class Meta:
        model = Repair_request
        exclude = ('status', )

templates/service/repair.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %} {% trans 'repair' %} {% endblock %}
{% block content %}
<div class="row page-titles">
    <div class="col-md-5 col-12 align-self-center">
        <h3 class="text-themecolor mb-0">{% trans 'repair' %}</h3>
    </div>
    <div class="col-md-7 col-12 align-self-center d-none d-md-flex justify-content-end">
        <ol class="breadcrumb mb-0 p-0 bg-transparent">
            <li class="breadcrumb-item"><a href="">{% trans 'repair' %}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'service:service_list' %}">{% trans 'services' %}</a></li>
            <li class="breadcrumb-item active d-flex align-items-center">{% trans 'home' %}</li>
        </ol>
    </div>
</div>
<div class="row">
    <div class="col-lg-3 col-md-6 pointer"
    hx-trigger="click" 
    hx-swap="innerHTML"
    hx-target="#displayData"
    hx-get="/service/get_data?service=repair&data=all">
        <div class="card">
            <div class="card-body">

                <div class="text-center">
                    <h6 class="text-muted mt-2 mb-2">{% trans 'total_requests_number' %}</h6>
                    <h2>{{total_count}}</h2>
                </div>

            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 pointer" hx-trigger="click" hx-get="/service/get_data?service=repair&data=on_hold"
        hx-target="#displayData" hx-swap="innerHTML">
        <div class="card">
            <div class="card-body">

                <div class="text-center">
                    <h6 class="text-muted mt-2 mb-2">{% trans 'on_hold' %}</h6>
                    <h2>{{on_hold_count}}</h2>
                </div>

            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 pointer" hx-trigger="click" hx-get="/service/get_data?service=repair&data=new"
        hx-target="#displayData" hx-swap="innerHTML">
        <div class="card">
            <div class="card-body">
                <div class="text-center">
                    <h6 class="text-muted mt-2 mb-2">{% trans 'new_requests' %}</h6>
                    <h2>{{new_count}}</h2>
                </div>

            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 pointer" hx-trigger="click"
        hx-get="/service/get_data?service=repair&data=late_services" hx-target="#displayData" hx-swap="innerHTML">
        <div class="card  border border-danger text-center">
            <div class="card-body">
                <div class="text-center">
                    <h6 class="text-muted mt-2 mb-2">{% trans 'late_requests' %}
                    </h6>
                    <h2>{{late_count}}</h2>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="card card-body" id="displayData">
    <div class="table-responsive">
        <table class="table search-table " id="serviceTable">
            <thead class="header-item bg-dark text-light text-center">
                <th>#</th>
                <th>{% trans 'req_number' %}</th>
                <th>{% trans 'customer_name' %}</th>
                <th>{% trans 'customer_phone '%}</th>
                <th>{%trans 'date'%}</th>
                <th>{% trans 'invoice_number'%}</th>
                <th>{% trans 'status' %}</th>
                <th>{% trans 'customer_type' %}</th>
                <th>{% trans 'seller' %}</th>
                <!-- <th></th> -->
            </thead>
            <tbody>
                <!-- row -->
                {% for service in services %}
                <tr class="search-items text-center ">
                    <td>{{forloop.counter}} </td>
                    <td>
                        <a href="{% url 'service:service_details' service.id %}">{{service.ref_number}}</a>
                    </td>


                    <td>{{service.customer}}</td>
                    <td>{{service.phone_number}}</td>
                    <td>{{service.created_at.date|date:"F j"}}</td>
                    <td>{% if service.invoice_number %} {{service.invoice_number}} {% else %} - {% endif%}</td>
                    <td>


                        <a href="{% url 'service:service_details' service.id %}">

                            {% if service.hold %}
                            <span class="badge bg-danger">{trans 'hold' }</span>
                            {% else %}
                            <span class="badge  
    
                        {% if service.status  == 'new' %}
                           bg-warning
                        {% elif service.status == 'under_process' %}
                            bg-primary
                        {% elif  service.status == 'done' or service.status  == 'closed' %}
                            bg-success
                        {% endif %} 
       
                           ">
                               
                           {{service.get_status_display}}
                            </span>
                            {% endif %}
                            </a>
                    </td>
                    <td>
                        {{service.get_customer_type_display}}
                    </td>
                    <td><a href="{% url 'users:user_details' service.created_by.id %}">{{service.created_by}}</a></td>
          
                </tr>
                {% endfor %}
                <!-- /.row -->

            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block script%}

<script src="https://unpkg.com/htmx.org@1.8.6"></script>
<script>
    $(document).ready(function () {
        $('#serviceTable').DataTable({
            pageLength: 50,
            ordering: false,
            scrollY: 350,
            "language": {
                "paginate": {
                    "next": "الصفحة التالية",
                    "previous": "الصفحة السابقة"
                },
                "emptyTable": "لا يوجد بيانات للعرض ",
                "info": "عرض _START_ الي _END_ من _TOTAL_ طلبات",
                "infoEmpty": "Showing 0 to 0 of 0 entries",
                "infoFiltered": "(تم البحث في  _MAX_ طلب)",
                "search": "البحث:",
                "zeroRecords": "لا يوجد بيانات مطابقة للبحث",
                "lengthMenu": "عرض _MENU_ طلب في الصفحة ",

            },
            "pagingType": "numbers"

        })
    })
</script>
{% endblock %}

templates/service/service_details.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %} تفاصيل طلب {{service.get_service_type_display}} رقم {{service.ref_number}} {% endblock %}
{% block content %}
<div class="row page-titles">
    <div class="col-md-5 col-12 align-self-center">
        <h3 class="text-themecolor mb-0"> {% trans 'req_details' %} {{service.ref_number}}
        </h3>
    </div>
    <div class="col-md-7 col-12 align-self-center d-none d-md-flex justify-content-end">
        <ol class="breadcrumb mb-0 p-0 bg-transparent">
            <li class="breadcrumb-item">{{service.ref_number}}</li>

            <li class="breadcrumb-item"><a {% if service.service_type == 'repair' %} href="{% url 'service:repair' %}"
                    {% elif  service.service_type == 'install' %} href="{% url 'service:install' %}"
                    {% endif %}>ال{{service.get_service_type_display}}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'service:service_list' %}">{% trans 'services' %}</a></li>
            <li class="breadcrumb-item active d-flex align-items-center">{% trans 'home' %}</li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-12 card ">
        {% include './partials/service_info.html' %}
    </div>
    <div class="col-md-12 ">
        <div class="card">
            <div class="card-body">
                {% if service.hold %}
                {% include './partials/hold.html' %}
                {% else %}
                <div class="btn-group d-flex flex-column flex-md-row gap-4">
                    {% if service.status == 'new' and service.service_type == 'install' and service.favourite == False %}
                    {% if request.user.remaining_qouta  or request.user.is_superuser or request.user.role == 'install_supervisor' %}
                    <form method="post" action="{% url 'service:favourite_service' %}">
                        {% csrf_token%}
                        <input type="hidden" name="service" value="{{service.id}}">
                        <button class="btn btn-info">{%trans 'add_to_favs' %}</button>
                    </form>
                    {% endif %}
                    {% endif %}

                    {% if service.status  == 'new' or service.status == 'under_process' %}
                    {% if service.service_type == 'repair' and service.status == 'under_process' and request.user.role == 'repair_supervisor' or request.user.is_superuser  %}
                    <button class="btn btn-info " data-bs-target="#hold_service" data-bs-toggle="modal"><i
                            data-feather="pause-circle"></i> {% trans 'hold' %} </button>
                    {% endif %}
                    {% endif %}

                    {% if request.user.is_superuser or request.user.role == 'admin' or request.user.role == 'install_supervisor' or request.user.role == 'repair_supervisor' %}
                    <button class="btn btn-info " data-bs-toggle="modal" data-bs-target="#change_status">
                        <i data-feather="edit"></i>
                        {% trans 'change_status' %} </button>
                    {% endif %}
                    {% if service.status == 'new' and request.user == service.created_by or request.user.is_superuser %}
                    <button class="btn btn-danger " data-bs-toggle="modal" data-bs-target="#delete_approve"><i
                            data-feather="trash-2"></i> {%trans  'delete' %} </button>
                    {% endif %}
                    {% if service.status == 'under_process'  %}
                    {% if request.user.role == 'repair_supervisor' or request.user.role == 'install_supervisor'   or request.user == appointment.technician or request.user.is_superuser%}
                    <button class="btn btn-success " data-bs-target="#confirm_excution" data-bs-toggle="modal"> <i
                            data-feather="check-circle"></i> {% trans 'confirm_exec' %}</button>
                    {% endif %}
                    {% endif %}
                    {% if service.status == 'done'   %}
                    {%   if request.user.role == 'repair_supervisor' or request.user.role == 'install_supervisor' or request.user.is_superuser %}
                    <a class="btn btn-success"
                        href="/service/update_status?service={{service.id}}&status=closed"><i
                            data-feather="check-circle"></i> {%trans  'confirm_exec_close' %} </a>
                    {% endif %}
                    {% endif %}
                </div>
                {% endif %}
            </div>
        </div>

        {% if service.has_open_sp_requests %}
        <div class="card card-body">
            <h3>{% trans 'sp_requests' %}</h3>
            {% for req in service.sp_request.all %}
            <div>
                <div class="card shadow-sm">
                    <div class="card-body">
                        <div class="row g-2 mx-4">
                            <div class="col-sm-6 p-2 border-bottom mb-4">
                                <span class="text-muted">{% trans 'requested_parts' %}:</span>
                                <span class="ms-2 fw-bold">{{req.requested_parts}}</span>
                            </div>
                            {% if req.details %}
                            <div class="col-sm-6 p-2 border-bottom mb-4">
                                <span class="text-muted">{% trans 'details' %}:</span>
                                <span class="ms-2 fw-bold">{{req.details}}</span>
                            </div>
                            {% endif %}
                            <div class="col-sm-6 p-2 border-bottom mb-4">
                                <span class="text-muted">{% trans 'created_at' %}:</span>
                                <span class="ms-2 fw-bold">{{req.created_at}}</span>
                            </div>
                            <div class="col-sm-6 p-2 border-bottom mb-4">
                                <span class="text-muted">{% trans 'created_by' %}:</span>
                                <span class="ms-2 fw-bold">{{req.created_by}}</span>
                            </div>
                            <div class="col-12 p-2 border-bottom mb-4">
                                <span class="text-muted">{% trans 'recieved' %}:</span>
                                <span class="ms-2">
                                    {% if req.status == 'pending' %}
                                    <span class="badge bg-danger">{% trans 'no' %}</span>
                                    {% elif req.status == 'recieved' %}
                                    <span class="badge bg-success">{% trans 'yes' %}</span>
                                    {% endif %}
                                </span>
                            </div>
                        </div>
                        {% if req.status == 'pending' and request.user.is_superuser or request.user.role == 'repair_supervisor' %}
                        <div class="d-flex justify-content-end">
                            <form action="{% url 'service:confirm_sp_recievce' %}" method="post" class="m-0">
                                {% csrf_token %}
                                <input type="hidden" name="sp_request" value="{{req.id}}">
                                <button type="submit" class="btn btn-success">
                                    <i class="bi bi-check-circle"></i> {% trans 'confirm_recieve' %}
                                </button>
                            </form>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}


        {% if service.status == 'new'  %}
        {% if  request.user.role == 'repair_supervisor' or request.user.role == 'install_supervisor' or request.user.is_superuser  %}
        <div class="card">
            <div class="card-body">
                <h3 class="text-start mb-2">{% trans 'set_appointment'%}</h3>
                <form action="{% url 'service:set_appointment' %}" method="post">
                    <input type="hidden" name="service" value="{{service.id}}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="">{% trans 'technician' %} </label>
                        <select name="technician" id="" class="form-control" required>
                            <option value="" selected disabled> {% trans 'choose_from_list' %}</option>
                            {% for tech in technician %}
                            <option value="{{tech.id}}">{{tech.name}}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group my-2">
                        <label for="">{% trans 'notes' %}</label>
                        <textarea name="notes" class="form-control" id="" cols="30" rows="2"></textarea>
                    </div>
                    <div class="d-flex justify-content-end">

                        <input type="submit" value="{% trans 'save' %}" class="btn btn-info w-25">
                    </div>
                </form>
            </div>

        </div>
        {% endif %}
        {% elif service.status == 'under_process' and service.hold == False  and service.appointment_set %}
        <div class="card">
            <div class="card-body">
                <h3>{% trans 'appointment' %}</h3>
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <div class="row g-2 mx-4">
                                <div class="col-sm-6 p-2 border-bottom mb-4">
                                    <span class="text-muted">{% trans 'date' %}:</span>
                                    <span class="ms-2">{{appointment.date}}</span>
                                </div>
                
                                <div class="col-sm-6 p-2 border-bottom mb-4">
                                    <span class="text-muted">{% trans 'technician' %}:</span>
                                    <span class="ms-2"><a href="">{{appointment.technician.name}}</a></span>
                                </div>
                
                                <div class="col-sm-6 p-2 border-bottom mb-4">
                                    <span class="text-muted">{% trans 'technician_phone' %}:</span>
                                    <span class="ms-2"><a href="">{{appointment.technician.phone_number}}</a></span>
                                </div>
                            </div>
                        </div>
                    </div>


                <div class="text-end">
                    {% if request.user.role == 'install_supervisor' or reques.user.role == 'repair_supervisor' or request.user.is_superuser %}
                    <button class="btn btn-info my-2 " data-bs-target="#chnage-appointment"
                        data-bs-toggle="modal">{% trans 'change_appointment' %}</button>
                    {% endif %}
                </div>
            </div>
        </div>

        {% endif %}


    </div>
</div>

{% include './modals/service_modals.html' %}
{% endblock %}



{% block script %}
<script>
    function reasonSelect() {
        let el = document.getElementById('hold_reason_select')
        let selectedOption = el.selectedOptions[0]
        let sp_input_group = document.getElementById('spare_parts_input_group')
        let sp_input = document.getElementById('sp_input')
        if (selectedOption.value == 'spare_parts') {
            sp_input_group.classList.toggle('hide')
            sp_input.setAttribute('required', '')


        } else {
            sp_input_group.classList.add('hide');
            sp_input.removeAttribute('required')

        }
    }
</script>
{% endblock %}