api/urls.py
from django.urls import path
from . import views 


app_name = 'api'
urlpatterns = [
    path('customers' , views.CustomerList.as_view() , name='customer_list')   ,
    path('sp_request/<int:pk>' , views.SparePartRequestDetails.as_view() , name='sp_request_details')    ,
]

core/urls.py
from . import views
from django.urls import path


app_name = 'core'
urlpatterns = [
    path('' , views.Index.as_view() ,name='index'),
    path('customers' , views.CustomerList.as_view() , name='customer_list'),
    path('customers/new' , views.CreateCustomerView.as_view() , name='add_customer'),
    path('customers/<int:pk>/details' , views.CustomerDetails.as_view() , name='customer_details'),
    path('archive' , views.Archive.as_view() , name='archive'),
    path('reports' , views.Reports.as_view() , name='reports'),
    path('index_data' , views.index_data , name='index_data'),
    
    path('service_chart' , views.ServiceChartView.as_view() , name='service_chart_view'),
    path('sales_performance_chart' , views.SalesPerformance.as_view() , name='sales_performance_chart'),
    path('daily_performance_chart' , views.DailyPerformance.as_view() , name='daily_performance_chart'),
]

quarter_crm/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('core.urls' ,namespace='core')),
    path('api/' , include('api.urls' ,namespace='api')),
    path('service/' , include('service.urls' ,namespace='service')),
    path('auth/' , include('users.urls' , namespace='users')) , 
    path('quarter/', include('quarter.urls' , namespace='quarter') ) ,
    path('i18n/', include('django.conf.urls.i18n')),
    path('__debug__/', include('debug_toolbar.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from django.urls import path
from . import views


app_name = 'service'
urlpatterns = [
    
    path('' , views.ServiceListView.as_view() , name = 'service_list'),
    path('new' , views.CreateService.as_view() , name = 'add_service'),
    path('<int:pk>/details' , views.ServiceDetails.as_view() , name = 'service_details'),
    path('<int:pk>/delete' , views.DeleteService.as_view() , name='delete_service') ,
    path('update_status' , views.UpdateServiceStatus.as_view() , name='update_service_status') ,
    path('hold_service' , views.HoldService.as_view() , name='hold_service') ,
    path('favourite_service' , views.FavouriteService.as_view() , name='favourite_service'),
    path('set_appointment' , views.SetAppointment.as_view() , name='set_appointment'),
    path('confirm_excution' , views.ConfirmExcution.as_view() , name='confirm_excution'),
    path('spare_part_request' , views.SparePartRequest.as_view() , name='spare_part_request'),
    path('sp/confirm_recieve' , views.ConfirmSparePartRecieve.as_view() , name='confirm_sp_recievce') , 
    path('install' , views.InstallListView.as_view() , name='install'),
    path('repair' , views.RepairListView.as_view() , name='repair'),
    # htmx views 
    path('service_request' , views.service_request , name='service_request'),
    path('get_data' , views.render_service_data , name='get_data')
]

users/urls.py
from django.urls import path
from . import views 
from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('login' , views.Login.as_view() , name='login') ,
    path('logout' ,LogoutView.as_view()  , name='logout'),
    
    path('user/list' , views.UserList.as_view() , name='user_list'),
    path('user/<int:pk>' , views.UserDetails.as_view() , name='user_details'),
    path('user/new' , views.CreateUser.as_view() , name='create_user'),
    path('user/<int:pk>/delete' , views.DeleteUser.as_view() , name='delete_user'),
    path('user/edit'  , views.EditUserDetails.as_view() , name='edit_user_details'),
    path('user/change_password' , views.ChangeUserPassword.as_view() , name='change_password'),
    
    # validate username 
    path('validate_username' , views.validate_username , name='validate_username')
]

core/models.py
from django.db import models
from django.conf import settings


# Create your models here.
User = settings.AUTH_USER_MODEL

class Customer(models.Model):
    name = models.CharField(max_length=255 ) 
    phone_number = models.CharField(max_length= 15 , unique = True )
    address = models.CharField(max_length= 255 , blank=True)
    city = models.CharField(max_length=50 , blank=True)
    created_by = models.ForeignKey(User , on_delete=models.SET_NULL , null =True , blank = True )
    created_at = models.DateTimeField(auto_now_add=True)
    
    
    def __str__(self):
        return self.name
    

class LateDays(models.Model):
    days = models.PositiveIntegerField(default=3)
    
    class Meta:
        verbose_name_plural = 'Late Days'
    
    def __str__(self):
        return f'late days are {self.days}'

quarter/models.py
from django.db import models
from users.models import User
from .choices import PORJECT_STATUS_CHOICES , NEGOTIATION_STATUS_CHOICES
from datetime import datetime
from django.db.models import Max
import uuid
import os 
# Create your models here.
    
def get_file_path(instance, filename):
    """Generate a unique filename for the uploaded file."""
    ext = filename.split('.')[-1]
    filename = f"{uuid.uuid4()}.{ext}"
    return os.path.join('files/quarter', filename)



def generate_ref_number():
    prefix = 'Q'
    year = str(datetime.now().year)[-2:]

    last_ref_number =   QuarterProject.objects.filter(
        ref_number__startswith=f'{prefix}{year}'
    ).aggregate(Max('ref_number'))['ref_number__max']

    if not last_ref_number:
        return f'{prefix}{year}001'

    last_number = int(last_ref_number[-3:])
    new_number = f'{last_number+1:03d}'
    return f'{prefix}{year}{new_number}'



class QuarterProject(models.Model):
    ref_number = models.CharField(max_length=12 , default=generate_ref_number, unique=True)
    name = models.CharField(max_length=255 )
    phone_number = models.CharField(max_length=15)
    address =models.CharField(max_length=255 , blank=True , null = True )
    status = models.CharField(max_length=20 , default='new' , choices = PORJECT_STATUS_CHOICES)
    created_by = models.ForeignKey(User , on_delete=models.SET_NULL , null = True )
    created_at = models.DateTimeField(auto_now_add=True )
    last_update = models.DateTimeField(auto_now=True )
    closed_date = models.DateTimeField(null = True , blank = True )
    rep = models.ForeignKey(User , on_delete=models.SET_NULL , null=True , blank=True , related_name='project_rep')
    

    def __str__(self) :
        return self.ref_number
    
    class Meta:
        ordering = ['-created_at']
    
class Negotiation(models.Model):
    project = models.ForeignKey(QuarterProject , on_delete=models.CASCADE)
    created_by = models.ForeignKey(User ,on_delete=models.SET_NULL , null = True)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10 , choices=NEGOTIATION_STATUS_CHOICES , default='current')
    
    
class ProjectFiles(models.Model):
    project = models.ForeignKey(QuarterProject , on_delete=models.CASCADE)
    created_by = models.ForeignKey(User , on_delete=models.SET_NULL , null = True )
    created_at = models.DateTimeField(auto_now_add=True)
    files = models.ManyToManyField('File')
    
    class Meta:
        verbose_name_plural = 'Project Files'
        
    def __str__(self):
        return f'{self.project} Excution files . '


class File(models.Model):
    file = models.FileField(upload_to=get_file_path)
    

service/models.py
from django.db import models
from .choices import SERVICE_TYPE, CUSTOMER_TYPE, REQUEST_STATUS, SPARE_PART_STATUS
from core.models import Customer
from django.conf import settings
import random
from .utils import generate_ref_number
from datetime import timedelta, date
from django.utils import timezone
from django.db.models import Case, When
from .managers import ServiceManager, AppointmentManager
from core.models import LateDays
import uuid
import os 
# Create your models here.
    
def get_file_path(instance, filename):
    """Generate a unique filename for the uploaded file."""
    ext = filename.split('.')[-1]
    filename = f"{uuid.uuid4()}.{ext}"
    return os.path.join('files/', filename)



User = settings.AUTH_USER_MODEL

status_ordering = Case(
    When(status='new', then=0),
    When(status='under_process', then=1),
    When(status='done', then=2),
    When(status='completed', then=3),
    output_field=models.IntegerField(),
)



class Service(models.Model):
    ref_number = models.CharField(max_length=15, blank=True, null=True)
    customer = models.CharField(max_length=255  , null = True , blank=True )
    phone_number = models.CharField(max_length=255 , null = True , blank=True )
    address = models.CharField(max_length=255, blank=True, null=True)
    customer_type = models.CharField(
        max_length=15, choices=CUSTOMER_TYPE, default='cash')
    service_type = models.CharField(max_length=10, choices=SERVICE_TYPE)
    machine_type = models.CharField(max_length=100, blank=True, null=True)
    invoice_number = models.CharField(max_length=30, blank=True, null=True)
    status = models.CharField(
        max_length=15, choices=REQUEST_STATUS, default='new')
    notes = models.CharField(max_length=255, blank=True, null=True)
    company = models.ForeignKey(User, on_delete=models.SET_NULL,
                                null=True, blank=True, related_name='warranty_company')
    ac_count = models.PositiveIntegerField(default= 0, blank=True , null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    last_update = models.DateTimeField(auto_now=True)
    code = models.CharField(unique=True, max_length=12,
                            blank=True, null=True, editable=False)
    favourite = models.BooleanField(default=False)
    hold = models.BooleanField(default=False)
    archive = models.BooleanField(default=False)

    objects = ServiceManager()

    def __str__(self):
        return self.ref_number

    def save(self, *args, **kwargs):
        if not self.code:
            while True:
                code = str(random.randint(1000, 9999))
                if not Service.objects.filter(code=code , archive = False).exists():
                    self.code = code
                    break
        if not self.ref_number:
            self.ref_number = generate_ref_number(self.service_type)
        super().save(*args, **kwargs)

    @property
    def late(self):
        '''
        Return True if order is late 
        late order has passed --latedays settings default == 3 -- and status is still new 
        '''
        days = LateDays.objects.last().days
        three_days_ago = timezone.now() - timedelta(days=days - 1)
        return self.status == 'new' and self.created_at <= three_days_ago and self.hold == False

    def has_open_sp_requests(self):
        '''
        Checks if service has unrecieved spare parts requests 
        '''
        return self.sp_request.filter(status='pending').exists()


class File(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    file = models.FileField(upload_to=get_file_path)
    cretaed_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self) -> str:
        return 'Service File '


class Appointment(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    technician = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True, related_name='appointment_tech')
    date = models.DateField()
    notes = models.CharField(max_length=300, blank=True, null=True)
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    objects = AppointmentManager()

    def __str__(self):
        return f'{self.service} Appointment !'

    @property
    def today(self):
        today = date.today()
        return self.date == today


class ExcutionFile(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    file = models.FileField(upload_to=get_file_path)
    cretaed_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.service} exec file . '


class HoldReason(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    reason = models.TextField(max_length=300, blank=True, null=True)
    details = models.TextField(max_length=300 , blank = True , null = True )
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    canceled_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True, related_name='hold_canceled_by')
    canceled_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f'{self.service} Hold Reason !'


class HoldFile(models.Model):
    hold_reason = models.ForeignKey(HoldReason, on_delete=models.CASCADE)
    file = models.FileField(upload_to=get_file_path)
    cretaed_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)


# spare parts request :
class SparePartRequest(models.Model):
    service = models.ForeignKey(
        Service, on_delete=models.CASCADE, related_name='sp_request')
    requested_parts = models.CharField(max_length=255, blank=True, null=True)
    details = models.CharField(max_length=300, blank=True, null=True)
    status = models.CharField(
        max_length=15, choices=SPARE_PART_STATUS, default='pending')
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    recievied_at = models.DateTimeField(blank=True , null=True)
    recievied_by = models.ForeignKey(User , on_delete=models.SET_NULL , null=True ,blank=True , related_name='sp_recieved')

    class Meta:
        verbose_name = 'Spare Part Reauest'
        verbose_name_plural = 'Spare Part Reauests'

    def __str__(self):
        return f'{self.service} spare part request .'

core/forms.py
from django import forms
from . import models 

class CustomerForm(forms.ModelForm):
    class Meta :
        model = models.Customer
        fields = ['name' , 'phone_number' , 'address' , 'city' ]
        
        labels = {
            'name' : 'الاسم' ,
            'phone_number' : 'الجوال',
            'address': 'العنوان' , 
            'city' : 'المدينة'
        }
        
        widgets = {
            'name': forms.TextInput(attrs={'required': True}),
            'phone_number': forms.TextInput(attrs={'required': True}),
            'address': forms.TextInput(attrs={'required': True}),
            'city': forms.TextInput(attrs={'required': True}),
        }

templates/core/company_index.html
{% extends 'base.html' %}
{% block title %} الرئيسية {% endblock %}
{% block content %}
<div class="row">
    <div class="col-lg-4 col-md-6">
        <div class="card">
            <div class="card-body">
                
                <div class="text-center">
                    <h6 class="text-muted mt-2 mb-2">الطلبات</h6>
                    <h2>{{services.count}}</h2>
         
                </div>
                
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="card">
            <div class="card-body">
         
                    <div class="text-center">
                        <h6 class="text-muted mt-2 mb-2">طلبات الضمان</h6>
                        <h2>{{warranty.count}}</h2>
                    </div>
 
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="card">
            <div class="card-body">
         
                    <div class="text-center">
                        <h6 class="text-muted mt-2 mb-2">طلبات قطع الغيار</h6>
                        <h2>{{sp_requests.count}}</h2>
                       
                    </div>
 
            </div>
        </div>
    </div>
</div>

<div class="card card-body">
    <h3>الطلبات </h3>
    <div class="table-responsive">
        <table class="table search-table " id="serviceTable">
            <thead class="header-item bg-dark text-light text-center">
                <th>#</th>
                <th>رقم الطلب </th>
                <th>اسم العميل </th>
                <th>الجوال</th>
                <th>نوع الطلب </th>
                <th>التاريخ</th>
                <th>حالة الطلب </th>
                <th>Action</th>
            </thead>
            <tbody>
                <!-- row -->
                {% for service in services %}
                <tr class="search-items text-center">
                    <td>{{forloop.counter}} </td>
                    <td>
                        <a href="{% url 'service:service_details' service.id %}">{{service.ref_number}}</a>
                    </td>


                    <td> {{service.customer}}
                    </td>
                    <td>{{service.phone_number}}</td>
                    <td>
                        <span class="badge  
                        {% if service.service_type == 'install' %}
                        bg-primary
                        {% elif service.service_type == 'repair' %}
                        bg-secondary
                        {% endif %}
                        ">
    
                            {{service.get_service_type_display}}
                        </span>
                    </td>
                    <td>{{service.created_at.date|date:"F j"}}</td>
                    <td>
                        <span class="badge  
                    {% if service.status  == 'new' %}
                       bg-warning
                    {% elif service.status == 'under_process' %}
                        bg-primary
                    {% elif  service.status == 'done' or service.status  == 'closed' %}
                        bg-success
                    {% endif %} 
                       ">
                            {{service.get_status_display}}
                        </span>

                    </td>
                    <td>
                        <div class="action-btn">
                            <a href="" class="text-info edit"><i data-feather="eye"
                                    class="feather-sm fill-white"></i></a>
                            {% if perms.sales.delete_customer %}
                            <a class="text-dark delete ms-2" id="delete_approve_btn" data-url="" data-bs-toggle="modal"
                                data-bs-target="#delete_approve"><i data-feather="trash-2"
                                    class="feather-sm fill-white"></i></a>
                            {% endif %}
                        </div>
                    </td>
                </tr>
                {% endfor %}
                <!-- /.row -->

            </tbody>
        </table>
    </div>
</div>
<div class="card card-body">
    <h3>طلبات الضمان الخاصة بالشركة </h3>
    <div class="table-responsive">
        <table class="table search-table " id="warrantyTable">
            <thead class="header-item bg-dark text-light text-center">
                <th>#</th>
                <th>رقم الطلب </th>
                <th>اسم العميل </th>
                <th>الجوال</th>
                <th>نوع الطلب </th>
                <th>التاريخ</th>
                <th>حالة الطلب </th>

            </thead>
            <tbody>
                <!-- row -->
                {% for service in warranty %}
                <tr class="search-items text-center {% if service.late %} bg-light-danger {% endif %}">
                    <td>{{forloop.counter}} </td>
                    <td>
                        <a href="{% url 'service:service_details' service.id %}">{{service.ref_number}}</a>
                    </td>


                    <td> {{service.customer}}
                    </td>
                    <td>{{service.phone_number}}</td>
                    <td>
                        <span class="badge  
                        {% if service.service_type == 'install' %}
                        bg-primary
                        {% elif service.service_type == 'repair' %}
                        bg-secondary
                        {% endif %}
                        ">
    
                            {{service.get_service_type_display}}
                        </span>
                    </td>
                    <td>{{service.created_at.date|date:"F j"}}</td>
                    <td>
                        <span class="badge  
                    {% if service.status  == 'new' %}
                       bg-warning
                    {% elif service.status == 'under_process' %}
                        bg-primary
                    {% elif  service.status == 'done' or service.status  == 'closed' %}
                        bg-success
                    {% endif %} 
                       ">
                            {{service.get_status_display}}
                        </span>

                    </td>
            
                </tr>
                {% endfor %}
                <!-- /.row -->

            </tbody>
        </table>
    </div>
</div>
<div class="card card-body">
    <h3>طلبات قطع الغيار </h3>
    <div class="table-responsive">
        <table class="table search-table " id="">
            <thead class="header-item bg-dark text-light text-center">
                <th>#</th>
                <th>رقم الطلب </th>
                <th>اسم العميل </th>
                <th>نوع الجهاز </th>
                <th>القطعة</th>
                <th>التاريخ</th>
                <th>حالة الطلب </th>
 
            </thead>
            <tbody>
                <!-- row -->
                {% for req in sp_requests %}
                <tr class="text-center">
                    <td>{{forloop.counter}} </td>
                    <td>
                        <a href="{% url 'service:service_details' req.service.id %}">{{req.service.ref_number}}</a>
                    </td>


                    <td> <a>{{req.service.name}}</a>
                    </td>
                    <td>{{req.service.machine_type}}</td>
                    <td>{{req.requested_parts}}</td>

                    
                    <td>{{req.created_at.date|date:"F j"}}</td>
                    <td>
                        <span class="badge  
                    {% if req.status  == 'pending' %}
                       bg-warning
                    {% elif req.status == 'recieved' %}
                        
                        bg-success
                    {% endif %} 
                       ">
                            {{req.get_status_display}}
                        </span>

                    </td>
                    
                </tr>
                {% endfor %}
                <!-- /.row -->

            </tbody>
        </table>
    </div>
</div>
{% endblock %}
{% block script %}
  
<script>
        $(document).ready(function () {
            $('table' ).DataTable({
                pageLength: 25,
                ordering: false,
                "language": {
                    "paginate": {
                        "next": "الصفحة التالية",
                        "previous": "الصفحة السابقة"
                    },
                    "emptyTable": "لا يوجد بيانات للعرض ",
                    "info": "عرض _START_ الي _END_ من _TOTAL_ طلبات",
                    "infoEmpty": "Showing 0 to 0 of 0 entries",
                    "infoFiltered": "(تم البحث في  _MAX_ طلب)",
                    "search": "البحث:",
                    "zeroRecords": "لا يوجد بيانات مطابقة للبحث",
                    "lengthMenu": "عرض _MENU_ طلب في الصفحة ",
    
                },
                "pagingType": "numbers"
    
            })
        })

</script>
{% endblock script %}

templates/core/customer_details.html
{%extends 'base.html'%}
{% load static %}
{% block title %}{{customer}}{% endblock %}
{% block content %}
<div class="row page-titles">
    <div class="col-md-5 col-12 align-self-center">
        <h3 class="text-themecolor mb-0">بيانات العميل {{customer}}</h3>
    </div>
    <div class="col-md-7 col-12 align-self-center d-none d-md-flex justify-content-end">
        <ol class="breadcrumb mb-0 p-0 bg-transparent">
            <li class="breadcrumb-item active"><a href="">{{customer}}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'core:customer_list' %}">العملاء</a></li>
            <li class="breadcrumb-item d-flex align-items-center">{% trans 'home' %}</li>
        </ol>
    </div>
</div>

        <div class="card">
            <div class="card-header">
                بيانات العميل 
            </div>
            <div class="card-body">

                
                <ul class="list-group">
                    <li class="list-group-item text-muted">الاسم: <span class="text-primary">{{customer.name}}</span></li>
                    <li class="list-group-item text-muted">رقم الجوال : <span
                            class="text-primary">{{customer.phone_number}}</span>
                    </li>
                    <li class="list-group-item text-muted">العنوان : <span
                            class="text-primary">{{customer.address}}</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between">
                        <p class="text-muted"> المدينة
                            <span class="text-primary">{{customer.city}}</span> </p>

                    </li>
                    
                </ul>



            </div>
        </div>
        <div class="card ">
            <div class="card-header">
                الخدمات
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table search-table " id="serviceTable">
                        <thead class="header-item bg-dark text-light text-center">
                            <th>#</th>
                            <th>رقم الطلب </th>
                            <th>نوع الطلب </th>
                            <th>البائع</th>
                            <th>تاريخ الطلب</th>
                            <th>حالة الطلب </th>

                        </thead>
                        <tbody>
                            <!-- row -->
                            {% for service in customer.service_set.all %}
                            <tr class="search-items text-center">
                                <td>{{forloop.counter}} </td>
                                <td>
                                    <a href="{% url 'service:service_details' service.id %}">{{service.ref_number}}</a>
                                </td>
                
                                <td>
                                    <span class="badge  
                                    {% if service.service_type == 'install' %}
                                    bg-primary
                                    {% elif service.service_type == 'repair' %}
                                    bg-secondary
                                    {% endif %}
                                    ">
                
                                        {{service.get_service_type_display}}
                                    </span>
                                </td>
                                <td><a href="{% url 'users:user_details' service.created_by.id %}">{{service.created_by}}</a></td>
                                <td>{{service.created_at}}</td>
                                <td>
                                    <span class="badge  
                                {% if service.status  == 'new' %}
                                   bg-warning
                                {% elif service.status == 'under_process' %}
                                    bg-primary
                                {% elif  service.status == 'done' or service.status  == 'closed' %}
                                    bg-success
                                {% endif %} 
                                   ">
                                    {{service.get_status_display}}
                                    </span>
                
                                </td>
                                
                            </tr>
                            {% endfor %}
                            <!-- /.row -->
                
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
{% endblock %}

{% block script%}


<script>
    $(document).ready(function(){
        $('#serviceTable').DataTable({
            pageLength : 25,
            ordering: false ,

            "language": {
                "paginate": {
                    "next": "الصفحة التالية",
                    "previous": "الصفحة السابقة"
                            },
                    "emptyTable":     "لا يوجد بيانات للعرض ",
                    "info":           "عرض _START_ الي _END_ من _TOTAL_ طلبات",
                    "infoEmpty":      "Showing 0 to 0 of 0 entries",
                    "infoFiltered":   "(تم البحث في  _MAX_ طلب)",
                    "search":         "البحث:",
                    "zeroRecords":    "لا يوجد بيانات مطابقة للبحث",
                    "lengthMenu":     "عرض _MENU_ طلب في الصفحة ",
                
            },
            "pagingType": "numbers"

        })
    })
</script>
{% endblock %}

templates/core/tech_index.html
{% extends 'base.html'%}
{% block title %} الرئيسية{% endblock %}
{% block content %}
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                
                <div class="text-center">
                    <h6 class="text-muted mt-2 mb-2">مواعيد قادمة </h6>
                    <h2>{{upcoming_appointments.count}}</h2>
         
                </div>
                
            </div>
        </div>
    </div>
   
</div>

<div class="card card-body">
    <h3>مواعيد قادمة</h3>
    <div class="table-responsive">
        <table class="table search-table " id="serviceTable">
            <thead class="header-item bg-dark text-light text-center">
                <th>#</th>
                <th>رقم الطلب </th>
                <th>اسم العميل </th>
                <th>الجوال</th>
                <th>نوع الطلب </th>
                <th>تاريخ الزيارة</th>
         
            </thead>
            <tbody>
                <!-- row -->
                {% for app in upcoming_appointments %}
                <tr class="search-items text-center ">
                    <td>{{forloop.counter}} </td>
                    <td>
                        <a href="{% url 'service:service_details' app.service.id %}">{{app.service.ref_number}}</a>
                    </td>


                    <td> {{app.service.customer}}
                    </td>
                    <td><a href="tel:{{app.service.phone_number}}">{{app.service.phone_number}}</a></td>
                    <td>{{app.service.get_service_type_display}}</td>
                    <td>{{app.date}}</td>
                    
                </tr>
                {% endfor %}
                <!-- /.row -->

            </tbody>
        </table>
    </div>
</div>
{% endblock %}