api/urls.py
from django.urls import path
from . import views 


app_name = 'api'
urlpatterns = [
    path('customers' , views.CustomerList.as_view() , name='customer_list')   ,
    path('sp_request/<int:pk>' , views.SparePartRequestDetails.as_view() , name='sp_request_details')    ,
]

quarter/urls.py
from django.urls import path
from . import views

app_name = 'quarter'
urlpatterns = [
    path('' , views.ProjectList.as_view() , name='project_list'),
    path('new' , views.CreateProject.as_view() , name='create_project'),
    path('project/<int:pk>' , views.ProjectDetails.as_view() , name='project_details'),
    path('project/<int:pk>/update' , views.UpdateProject.as_view() , name='update_project'),
    path('project/<int:pk>/delete' , views.DeleteProject.as_view() , name='delete_project'),
    path('project/start_negotiation' , views.StartNegotiation.as_view() , name='start_negotiation'),
    path('project/negotiation_status' , views.NegotiationStatus.as_view() , name='negotiation_status'),
    path('project/attach_files' , views.AttachExcutionFiles.as_view() , name='attach_files'),
    path('project/confirm_project' , views.ConfirmProject.as_view() , name='confirm_project'),
    path('data' , views.get_data, name='get_data')
]

quarter_crm/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('core.urls' ,namespace='core')),
    path('api/' , include('api.urls' ,namespace='api')),
    path('service/' , include('service.urls' ,namespace='service')),
    path('auth/' , include('users.urls' , namespace='users')) , 
    path('quarter/', include('quarter.urls' , namespace='quarter') ) ,
    path('i18n/', include('django.conf.urls.i18n')),
    path('__debug__/', include('debug_toolbar.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quarter/models.py
from django.db import models
from users.models import User
from .choices import PORJECT_STATUS_CHOICES , NEGOTIATION_STATUS_CHOICES
from datetime import datetime
from django.db.models import Max
import uuid
import os 
# Create your models here.
    
def get_file_path(instance, filename):
    """Generate a unique filename for the uploaded file."""
    ext = filename.split('.')[-1]
    filename = f"{uuid.uuid4()}.{ext}"
    return os.path.join('files/quarter', filename)



def generate_ref_number():
    prefix = 'Q'
    year = str(datetime.now().year)[-2:]

    last_ref_number =   QuarterProject.objects.filter(
        ref_number__startswith=f'{prefix}{year}'
    ).aggregate(Max('ref_number'))['ref_number__max']

    if not last_ref_number:
        return f'{prefix}{year}001'

    last_number = int(last_ref_number[-3:])
    new_number = f'{last_number+1:03d}'
    return f'{prefix}{year}{new_number}'



class QuarterProject(models.Model):
    ref_number = models.CharField(max_length=12 , default=generate_ref_number, unique=True)
    name = models.CharField(max_length=255 )
    phone_number = models.CharField(max_length=15)
    address =models.CharField(max_length=255 , blank=True , null = True )
    status = models.CharField(max_length=20 , default='new' , choices = PORJECT_STATUS_CHOICES)
    created_by = models.ForeignKey(User , on_delete=models.SET_NULL , null = True )
    created_at = models.DateTimeField(auto_now_add=True )
    last_update = models.DateTimeField(auto_now=True )
    closed_date = models.DateTimeField(null = True , blank = True )
    rep = models.ForeignKey(User , on_delete=models.SET_NULL , null=True , blank=True , related_name='project_rep')
    

    def __str__(self) :
        return self.ref_number
    
    class Meta:
        ordering = ['-created_at']
    
class Negotiation(models.Model):
    project = models.ForeignKey(QuarterProject , on_delete=models.CASCADE)
    created_by = models.ForeignKey(User ,on_delete=models.SET_NULL , null = True)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10 , choices=NEGOTIATION_STATUS_CHOICES , default='current')
    
    
class ProjectFiles(models.Model):
    project = models.ForeignKey(QuarterProject , on_delete=models.CASCADE)
    created_by = models.ForeignKey(User , on_delete=models.SET_NULL , null = True )
    created_at = models.DateTimeField(auto_now_add=True)
    files = models.ManyToManyField('File')
    
    class Meta:
        verbose_name_plural = 'Project Files'
        
    def __str__(self):
        return f'{self.project} Excution files . '


class File(models.Model):
    file = models.FileField(upload_to=get_file_path)
    

quarter/forms.py
from django.forms import ModelForm
from .models import QuarterProject

class QuarterProjectForm(ModelForm):
    class Meta:
        model = QuarterProject
        fields = ['name', 'phone_number', 'address']
        labels = {
            'name': 'اسم العميل',
            'phone_number': 'الجوال',
            'address': 'الموقع',
        }

quarter/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.views import generic
from . import models
from .forms import QuarterProjectForm
from django.contrib import messages
from django.urls import reverse_lazy
from django.db.models import Q
from django.utils import timezone

# Create your views here.

# list view
class ProjectList(generic.ListView):
    model = models.QuarterProject
    template_name = 'quarter/project_list.html'
    context_object_name = 'projects'
    def get_context_data(self, **kwargs):
        kwargs['under_process'] = models.QuarterProject.objects.exclude(Q(status = 'new' )|Q(status = 'canceled') |Q(status = 'done'))
        return super().get_context_data(**kwargs)


class CreateProject(generic.CreateView):
    model = models.QuarterProject
    form_class = QuarterProjectForm
    success_url = reverse_lazy('quarter:project_list')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        messages.success(self.request, 'تم اضافة الطلب !')
        return super().form_valid(form)

    def form_invalid(self, form):
        print(form.errors)
        messages.error(self.request, 'خطأ يرجي المحاولة مرة اخري ')
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))


class UpdateProject(generic.UpdateView):
    model = models.QuarterProject
    form_class = QuarterProjectForm

    def form_valid(self, form):
        messages.success(self.request, 'تم التحديث !')
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse_lazy('quarter:project_details', kwargs={'pk': self.object.pk})


class DeleteProject(generic.DeleteView):
    model = models.QuarterProject
    success_url = reverse_lazy('quarter:project_list')

    def delete(self, request, *args,  **kwargs):
        messages.warning(request, 'تم حذف المشروع !!')
        return super().delete(request, *args, **kwargs)


class ProjectDetails(generic.DetailView):
    model = models.QuarterProject
    context_object_name = 'project'
    template_name = 'quarter/project_details.html'
    lookup_field = 'id'

    def get_context_data(self, **kwargs):
        project = self.object
        if project.projectfiles_set:
            kwargs['excution_files'] = project.projectfiles_set.last()
        return super().get_context_data(**kwargs)


# start negotiaion
class StartNegotiation(generic.View):
    def post(self, request):
        project = models.QuarterProject.objects.get(pk=request.POST['project'])
        negotiation = models.Negotiation(
            project=project,
            created_by=request.user
        )
        negotiation.save()
        project.status = 'negotiation'
        project.rep = request.user
        project.save()
        messages.success(request, 'بدأ المفاوضات  !!')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class NegotiationStatus(generic.View):
    def post(self, request):
        project = models.QuarterProject.objects.get(pk=request.POST['project'])
        negotiation = models.Negotiation.objects.get(
            pk=request.POST['negotiation'])
        if request.POST['status'] == 'approved':
            negotiation.status = 'approved'
            negotiation.save()
            project.status = 'waiting_designs'
            project.save()
            messages.success(request, 'تم الحفظ !')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        elif request.POST['status'] == 'rejected':
            negotiation.status = 'rejected'
            negotiation.save()
            project.status = 'canceled'
            project.save()
            messages.danger(request, 'تم الغاء الطلب  !')
            return redirect(reverse_lazy('quarter:projet_list'))


# attach designes
class AttachExcutionFiles(generic.View):
    def post(self, request):
        project = models.QuarterProject.objects.get(pk=request.POST['project'])
        excution = models.ProjectFiles(
            project=project,
            created_by=request.user
        )
        excution.save()

        if request.FILES:
            print('files')
            for file in request.FILES.getlist('file'):
                print(file)
                f = models.File(
                    file=file

                )
                f.save()
                excution.files.add(f)

        project.status = 'waiting_approval'
        project.save()
        messages.success(request, 'تم ارفاق الملفات .')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

# confirm work start


class ConfirmProject(generic.View):
    def post(self, request):

        project = models.QuarterProject.objects.get(pk=request.POST['project'])
        if project.status == 'under_process':
            project.status = 'done'
            project.closed_date = timezone.now()
            project.save()
        else:
            project.status = 'under_process'
            project.save()
        messages.success(request, 'تم تحديث الطلب  .')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


# update status

#htmx views 
def get_data(request):
    status = request.GET['status']
    if status == 'all':
        data = models.QuarterProject.objects.all()
    elif status == 'current':
        data = models.QuarterProject.objects.exclude(Q(status = 'new' )|Q(status = 'canceled') |Q(status = 'done'))
        
    template = 'quarter/partials/htmx/table.html'
    
    return render(request , template , {'projects':data})

templates/quarter/modals/create_project_modal.html
<div class="modal fade" tabindex="-1" id="quarter_request">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="mb-3 text-primary text-center">مشروع جديد</h4>
            </div>

        <div class="modal-body">
            <form action="{% url 'quarter:create_project' %}" method="post" id="install_form" class="needs-validation"
            enctype="multipart/form-data"  />
            {% csrf_token %}
        
            <div class="row">
    

                <div class="col-12 my-2">
                    <label for="" class="text-primary">الاسم</label>
                    <input type="text" name="name" id="" required class="form-control" />
    
                    <div class="invalid-feedback">
                        <p>العميل مطلوب </p>
                    </div>
                </div>
                <div class="col-12 my-2">
                    <label class="text-primary" for="">الموقع</label>
                    <input type="text" name="address" class="form-control" id="cust_address" required>
                    <div class="invalid-feedback">
                        <p>بيانات العميل مطلوبة </p>
                    </div>
                </div>
    
                <div class="col-12 my-2">
                    <label class="text-primary" for="">الهاتف</label>
                    <input type="text" name="phone_number" class="form-control" id="cust_phone" required >
                    <div class="invalid-feedback">
                        <p>بيانات العميل مطلوبة </p>
                    </div>
                </div>
    
                
            </div>
            
            <div class="modal-footer">
                <button type="submit" class="btn btn-info " > حفظ</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">الغاء</button>
            </div>
        </form>
        </div>
    </div>
    </div>

   
</div>



{% block script %}
<script>
(function () {
    'use strict'
  
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.querySelectorAll('.needs-validation')
  
    // Loop over them and prevent submission
    Array.prototype.slice.call(forms)
      .forEach(function (form) {
        form.addEventListener('submit', function (event) {
          if (!form.checkValidity()) {
            event.preventDefault()
            event.stopPropagation()
          }
  
          form.classList.add('was-validated')
        }, false)
      })
  })()
</script>
{% endblock %}

templates/quarter/modals/project_modals.html
<!-- edit modal -->
<div class="modal fade" tabindex="-1" id="edit_project">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="mb-3 text-primary text-center">تعديل بيانات المشروع</h4>
            </div>

        <div class="modal-body">
            <form action="{% url 'quarter:update_project' project.id %}" method="post" id="install_form" class="needs-validation"
            enctype="multipart/form-data"  novalidate />
            {% csrf_token %}
        
            <div class="row">
    

                <div class="col-12 my-2">
                    <label for="" class="text-primary">الاسم</label>
                    <input type="text" name="name" id="" value="{{project.name}}" required class="form-control" />
    
                    <div class="invalid-feedback">
                        <p>العميل مطلوب </p>
                    </div>
                </div>
                <div class="col-12 my-2">
                    <label class="text-primary" for="">الموقع</label>
                    <input type="text" name="address" class="form-control" value="{{project.address}}" id="cust_address" required>
                    <div class="invalid-feedback">
                        <p>بيانات العميل مطلوبة </p>
                    </div>
                </div>
    
                <div class="col-12 mt-2">
                    <label class="text-primary" for="">الهاتف</label>
                    <input type="text" name="phone_number" class="form-control"  value="{{project.phone_number}}" id="cust_phone" required >
                    <div class="invalid-feedback">
                        <p>بيانات العميل مطلوبة </p>
                    </div>
                </div>
    
                
            </div>
            
            <div class="modal-footer">
                <button type="submit" class="btn btn-info " > حفظ</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">الغاء</button>
            </div>
        </form>
        </div>
    </div>
    </div>

   
</div>
<!-- delete approve  -->
<div class="modal custom-modal fade" id="project_delete_approve" role="dialog" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <div class="form-header text-center ">  
                    <i class=" fas fa-trash-alt fa-3x my-3 text-danger"></i> 
                    <h3>تأكيد الحذف </h3>
                </div>
                <div class="modal-btn delete-action my-3">
                    <div class="row text-center">
                        <div class="col-6"> 
                            <form action=" {% url 'quarter:delete_project' project.id %}" method="POST" id="delete-form">
                                {% csrf_token%}
                                
                                <button type="submit" id="confirmed_delete" class="btn btn-danger continue-btn w-100">حذف</a>
                            </form>
                        </div>
                        <div class="col-6">
                            <a href="javascript:void(0);" data-bs-dismiss="modal" class="btn btn-primary cancel-btn w-100">الغاء</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% block script %}
<script>
(function () {
    'use strict'
  
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.querySelectorAll('.needs-validation')
  
    // Loop over them and prevent submission
    Array.prototype.slice.call(forms)
      .forEach(function (form) {
        form.addEventListener('submit', function (event) {
          if (!form.checkValidity()) {
            event.preventDefault()
            event.stopPropagation()
          }
  
          form.classList.add('was-validated')
        }, false)
      })
  })()
</script>
{% endblock %}