api/urls.py
from django.urls import path
from . import views 


app_name = 'api'
urlpatterns = [
    path('customers' , views.CustomerList.as_view() , name='customer_list')   ,
    path('sp_request/<int:pk>' , views.SparePartRequestDetails.as_view() , name='sp_request_details')    ,
]

quarter_crm/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('core.urls' ,namespace='core')),
    path('api/' , include('api.urls' ,namespace='api')),
    path('service/' , include('service.urls' ,namespace='service')),
    path('auth/' , include('users.urls' , namespace='users')) , 
    path('quarter/', include('quarter.urls' , namespace='quarter') ) ,
    path('i18n/', include('django.conf.urls.i18n')),
    path('__debug__/', include('debug_toolbar.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from django.urls import path
from . import views


app_name = 'service'
urlpatterns = [
    
    path('' , views.ServiceListView.as_view() , name = 'service_list'),
    path('new' , views.CreateService.as_view() , name = 'add_service'),
    path('<int:pk>/details' , views.ServiceDetails.as_view() , name = 'service_details'),
    path('<int:pk>/delete' , views.DeleteService.as_view() , name='delete_service') ,
    path('update_status' , views.UpdateServiceStatus.as_view() , name='update_service_status') ,
    path('hold_service' , views.HoldService.as_view() , name='hold_service') ,
    path('favourite_service' , views.FavouriteService.as_view() , name='favourite_service'),
    path('set_appointment' , views.SetAppointment.as_view() , name='set_appointment'),
    path('confirm_excution' , views.ConfirmExcution.as_view() , name='confirm_excution'),
    path('spare_part_request' , views.SparePartRequest.as_view() , name='spare_part_request'),
    path('sp/confirm_recieve' , views.ConfirmSparePartRecieve.as_view() , name='confirm_sp_recievce') , 
    path('install' , views.InstallListView.as_view() , name='install'),
    path('repair' , views.RepairListView.as_view() , name='repair'),
    # htmx views 
    path('service_request' , views.service_request , name='service_request'),
    path('get_data' , views.render_service_data , name='get_data')
]

service/models.py
from django.db import models
from .choices import SERVICE_TYPE, CUSTOMER_TYPE, REQUEST_STATUS, SPARE_PART_STATUS
from core.models import Customer
from django.conf import settings
import random
from .utils import generate_ref_number
from datetime import timedelta, date
from django.utils import timezone
from django.db.models import Case, When
from .managers import ServiceManager, AppointmentManager
from core.models import LateDays
import uuid
import os 
# Create your models here.
    
def get_file_path(instance, filename):
    """Generate a unique filename for the uploaded file."""
    ext = filename.split('.')[-1]
    filename = f"{uuid.uuid4()}.{ext}"
    return os.path.join('files/', filename)



User = settings.AUTH_USER_MODEL

status_ordering = Case(
    When(status='new', then=0),
    When(status='under_process', then=1),
    When(status='done', then=2),
    When(status='completed', then=3),
    output_field=models.IntegerField(),
)



class Service(models.Model):
    ref_number = models.CharField(max_length=15, blank=True, null=True)
    customer = models.CharField(max_length=255  , null = True , blank=True )
    phone_number = models.CharField(max_length=255 , null = True , blank=True )
    address = models.CharField(max_length=255, blank=True, null=True)
    customer_type = models.CharField(
        max_length=15, choices=CUSTOMER_TYPE, default='cash')
    service_type = models.CharField(max_length=10, choices=SERVICE_TYPE)
    machine_type = models.CharField(max_length=100, blank=True, null=True)
    invoice_number = models.CharField(max_length=30, blank=True, null=True)
    status = models.CharField(
        max_length=15, choices=REQUEST_STATUS, default='new')
    notes = models.CharField(max_length=255, blank=True, null=True)
    company = models.ForeignKey(User, on_delete=models.SET_NULL,
                                null=True, blank=True, related_name='warranty_company')
    ac_count = models.PositiveIntegerField(default= 0, blank=True , null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    last_update = models.DateTimeField(auto_now=True)
    code = models.CharField(unique=True, max_length=12,
                            blank=True, null=True, editable=False)
    favourite = models.BooleanField(default=False)
    hold = models.BooleanField(default=False)
    archive = models.BooleanField(default=False)

    objects = ServiceManager()

    def __str__(self):
        return self.ref_number

    def save(self, *args, **kwargs):
        if not self.code:
            while True:
                code = str(random.randint(1000, 9999))
                if not Service.objects.filter(code=code , archive = False).exists():
                    self.code = code
                    break
        if not self.ref_number:
            self.ref_number = generate_ref_number(self.service_type)
        super().save(*args, **kwargs)

    @property
    def late(self):
        '''
        Return True if order is late 
        late order has passed --latedays settings default == 3 -- and status is still new 
        '''
        days = LateDays.objects.last().days
        three_days_ago = timezone.now() - timedelta(days=days - 1)
        return self.status == 'new' and self.created_at <= three_days_ago and self.hold == False

    def has_open_sp_requests(self):
        '''
        Checks if service has unrecieved spare parts requests 
        '''
        return self.sp_request.filter(status='pending').exists()


class File(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    file = models.FileField(upload_to=get_file_path)
    cretaed_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self) -> str:
        return 'Service File '


class Appointment(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    technician = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True, related_name='appointment_tech')
    date = models.DateField()
    notes = models.CharField(max_length=300, blank=True, null=True)
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    objects = AppointmentManager()

    def __str__(self):
        return f'{self.service} Appointment !'

    @property
    def today(self):
        today = date.today()
        return self.date == today


class ExcutionFile(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    file = models.FileField(upload_to=get_file_path)
    cretaed_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.service} exec file . '


class HoldReason(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    reason = models.TextField(max_length=300, blank=True, null=True)
    details = models.TextField(max_length=300 , blank = True , null = True )
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    canceled_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True, related_name='hold_canceled_by')
    canceled_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f'{self.service} Hold Reason !'


class HoldFile(models.Model):
    hold_reason = models.ForeignKey(HoldReason, on_delete=models.CASCADE)
    file = models.FileField(upload_to=get_file_path)
    cretaed_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)


# spare parts request :
class SparePartRequest(models.Model):
    service = models.ForeignKey(
        Service, on_delete=models.CASCADE, related_name='sp_request')
    requested_parts = models.CharField(max_length=255, blank=True, null=True)
    details = models.CharField(max_length=300, blank=True, null=True)
    status = models.CharField(
        max_length=15, choices=SPARE_PART_STATUS, default='pending')
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    recievied_at = models.DateTimeField(blank=True , null=True)
    recievied_by = models.ForeignKey(User , on_delete=models.SET_NULL , null=True ,blank=True , related_name='sp_recieved')

    class Meta:
        verbose_name = 'Spare Part Reauest'
        verbose_name_plural = 'Spare Part Reauests'

    def __str__(self):
        return f'{self.service} spare part request .'

templates/service/modals/install_modal.html
{% load i18n %}
{% load static %}
{% load widget_tweaks %}
<div class="modal fade" tabindex="-1" id="install_request">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="mb-3 text-primary text-center">{% trans "new_install_request" %}</h4>
            </div>

        <div class="modal-body">
            <form action="{% url 'service:add_service' %}" method="post" id="install_form" class="needs-validation"
            enctype="multipart/form-data"  />
            {% csrf_token %}
            <input type="hidden" name="service_type" value="install">
            <input type="hidden" name="customer_type" value="cash">
            <div class="row">
    
                <div class="form-check col-12 mx-2">
                    {% if request.user.remaining_qouta  or request.user.is_superuser or request.user.role == 'install_supervisor' %}
                    <input class="form-check-input" name="favourite" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label fw-bold text-success mx-1" for="flexCheckDefault">
                        {% trans "add_to_favs" %}
                    </label>
                    {% endif %}
                </div>
                <div class="col-12 my-2">
                    <label for="" class="text-primary">{% trans 'customer_name' %}</label>
                    <input type="text" name="customer" id="" required class="form-control" />
    
                    <div class="invalid-feedback">
                        <p>{% trans "field_required" %}</p>
                    </div>
                </div>
                <div class="col-12 my-2">
                    <label class="text-primary" for="">{%trans 'address' %}</label>
                    <input type="text" name="address" class="form-control" id="cust_address" required>
                    <div class="invalid-feedback">
                        <p>{% trans "field_required" %}</p>
                    </div>
                </div>
    
                <div class="col-12 my-2">
                    <label class="text-primary" for="">{% trans "phone" %}</label>
                    <input type="text" name="phone_number" class="form-control" id="cust_phone" required>
                    <div class="invalid-feedback">
                        <p>{% trans "field_required" %}</p>
                    </div>
                </div>
    
                <div class="col-12 my-2">
                    <label class="text-primary" for="">{% trans "invoice_number" %}</label>
                    <input type="text" name="invoice_number" id="" class="form-control">
    
                    <div class="invalid-feedback">
                        <p> </p>
                    </div>
                </div>
    
                <div class="col-12 my-2">
                    <label class="text-primary" for="">{% trans "ac_count" %}</label>
                    <input type="number" name="ac_count" id="" class="form-control">
    
                    <div class="invalid-feedback">
                        <p> </p>
                    </div>
                </div>
    
                <hr class="m-2">
                <div class="col-12">
                    <label class="text-primary" for="">{%trans "notes" %}/{% trans "details" %}</label>
                    <textarea name="notes" id="" cols="3" rows="3" class="form-control"></textarea>
                </div>
                <hr class="m-2">
                <div class="col-12">
                    <label class="text-primary" for="">{% trans "attache_file" %}</label>
                    <input type="file" name="file" id="" multiple>
                </div>
            </div>
            
            <div class="modal-footer">
                <button type="submit" class="btn btn-info " > {%trans 'save' %}</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans "cancel" %}</button>
            </div>
        </form>
        </div>
    </div>
    </div>

   
</div>


{% block script %}


{% endblock %}

templates/service/modals/service_modals.html
{% load i18n %}
<!-- Hold service  -->

<div class="modal custom-modal fade" id="hold_service" role="dialog" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <div class="form-header text-center ">
                    <h3>{% trans 'hold_request'%}</h3>
                </div>
                <div class="modal-btn delete-action mt-3">
                    <div class="">

                        <form action="{% url 'service:hold_service' %}" method="POST" enctype="multipart/form-data"
                            class="needs-validation" novalidate>
                            {% csrf_token%}
                            <input type="hidden" name="service" value="{{service.id}}">
                            {% if service.service_type == 'repair'%}
                            <div class="form-group">
                                <label for="">{% trans 'hold_reason' %}</label>
                                <select name="reason" id="hold_reason_select" class="form-control" onchange="reasonSelect()">
                                    <option value="" disabled selected>{% trans 'choose' %} {%trans 'hold_reason'%} </option>
                                    <option value="spare_parts">{%trans  'sp_request' %}</option>
                                    <option value="other">{% trans 'other' %}</option>
                                </select>
                            </div>
                            {% else %}

                            <div class="form-group">
                                <label for="">{% trans 'choose' %} {%trans 'hold_reason'%} </label>
                                <input type="text" name="reason" class="form-control" id="">  
                            </div>

                            {% endif %}

                            
                            <div class="form-group hide" id="spare_parts_input_group">
                                <label for="">{% trans 'requested_parts' %}</label>
                                <input type="text" name="spare_parts" id="sp_input" class="form-control">
                                <p class="invalid-feedback"> {% trans 'requested_parts_required' %}</p>
                            </div>
                            <div class="form-group">
                                <label for="">{% trans 'details' %}</label>
                                <textarea name="hold_reason" id="" cols="30" rows="3" required
                                    class="form-control"></textarea>
                                <p class="invalid-feedback">{%trans  'reason_required' %} !! </p>
                            </div>
                            <div class="form-group my-3">
                                <label for="">{% trans 'attache_file'%}</label>
                                <input type="file" name="file" class="form-control" multiple id="">
                            </div>

                            <div class="d-flex mt-3 gap-3">
                                <button type="submit" class="btn btn-info continue-btn  w-100">{% trans 'save' %}</button>

                                <a href="javascript:void(0);" data-bs-dismiss="modal"
                                    class="btn btn-secondary cancel-btn w-100">{% trans 'cancel' %}</a>
                            </div>

                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<!-- confirm delete  -->
<div class="modal custom-modal fade" id="delete_approve" role="dialog" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <div class="form-header text-center ">
                    <i class=" fas fa-trash-alt fa-3x my-3 text-danger"></i>
                    <h3>{%trans  'confirm_delete_request' %} {{service.ref_number}}</h3>
                </div>
                <div class="modal-btn delete-action my-3">
                    <div class="row text-center">
                        <div class="col-6">
                            <form action="{% url 'service:delete_service' service.id %}" method="POST" id="delete-form">
                                {% csrf_token%}

                                <button type="submit" id="confirmed_delete"
                                    class="btn btn-danger continue-btn w-100">{% trans 'delete' %}</a>
                            </form>
                        </div>
                        <div class="col-6">
                            <a href="javascript:void(0);" data-bs-dismiss="modal"
                                class="btn btn-secondary cancel-btn w-100">{% trans 'cancel' %}</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Change service status  -->
<div class="modal custom-modal fade" id="change_status" role="dialog" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <div class="form-header text-center ">

                    <h3>{% trans 'change_status' %} {{service.ref_number}}</h3>
                    <h5>{% trans 'current_status' %}:
                        <span class="badge pill-rounded 
                        
                    {% if service.status  == 'new' %}
                       bg-warning
                    {% elif service.status == 'under_process' %}
                        bg-primary
                    {% elif  service.status == 'done' or service.status  == 'closed' %}
                        bg-success
                    {% endif %} ">{{service.get_status_display}}</span>
                    </h5>
                </div>
                <div class="modal-btn delete-action">
                    <div class="row ">
                        <form action="{% url 'service:update_service_status' %}" method="POST">
                            <input type="hidden" name="service" value="{{service.id}}">
                            {% csrf_token%}
                            <label for="">{% trans 'status' %} : </label>
                            <select name="status" id="" class="form-control">
                                {% for k ,v in status_choices  %}

                                <option value="{{k}}" {% if service.status == k %} selected {% endif %}>{{v}}</option>
                                {% endfor %}
                            </select>
                            <div class="d-flex mt-3 gap-3">
                                <button type="submit" class="btn btn-info continue-btn  w-100">{% trans 'save' %}</button>

                                <a href="javascript:void(0);" data-bs-dismiss="modal"
                                    class="btn btn-secondary cancel-btn w-100">{% trans 'cancel'%}</a>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Edit appointments  -->
<div id="chnage-appointment" role="dialoge" tabindex="-1" class="modal custom-modal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">{% trans 'change_appointment' %}</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'service:set_appointment' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="service" value="{{service.id}}">
                    <div class="form-group">
                        <label for="">{% trans 'technician' %}</label>
                        <select name="technician" id="" class="form-control" required>
                            <option value="" selected disabled>{%trans 'choose_from_list' %} </option>
                            {% for tech in technician %}
                            <option value="{{tech.id}}" {% if tech.id == appointment.technician.id %} selected {% endif %} >{{tech.name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group my-2">
                        <label for="">{% trans 'notes' %}</label>
                        <textarea name="notes" class="form-control" id="" cols="30" rows="2"></textarea>
                    </div>
                    <input type="submit" value="{% trans 'save' %}" class="btn btn-info w-100">
                </form>
            </div>
        </div>
    </div>
</div>
<!-- Confirm excution -->
<div id="confirm_excution" role="dialoge" tabindex="-1" class="modal custom-modal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

            <div class="modal-header">
                
                <h2 class="modal-title" id="">{% trans 'confirm_exc' %}</h2>
                <button type="button" class="close btn btn-secondary" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'service:confirm_excution' %}" method="post" novalidate class="need-validation" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" name="service" value="{{service.id}}">
                    <div class="form-group my-2">
                        <label for="" class="text-primary">{% trans 'exec_code' %}</label>
                        <input type="text" name="code" id="" class="form-control">
                        <p class="invalid-feedback">{% trans 'exec_code_required' %}</p>
                        <p class="text-muted text-start">{% trans 'code_sent_message' %} </p>
                    </div>
                    <div class="form-group my-2">
                        <label for="" class="text-primary"> {% trans 'attach_exec_files'%}</label>
                        <input type="file" name="file" multiple id="" class="form-control" required />
                    </div>
                    <div class="form-group my-2">
                        <label for="" class="text-primary">{% trans 'notes' %}</label>
                        <textarea name="notes" class="form-control" id="" cols="30" rows="2"></textarea>
                    </div>
                    <input type="submit" value="{% trans 'save' %}" class="btn btn-info w-100">
                </form>
            </div>
        </div>
    </div>
</div>

<!-- spare parts request  -->
<div id="spare_parts_request" role="dialoge" tabindex="-1" class="modal custom-modal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

            <div class="modal-header">
                <h2 class="modal-title" id="">{%trans 'sp_request' %} </h2>
                <button type="button" class="close btn btn-secondary" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'service:spare_part_request' %}" method="post"  enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" name="service" value="{{service.id}}">
                    <div class="form-group my-2">
                        <label for="">{% trans 'requested_parts'%}</label>
                        <input type="text" name="requested_parts" id="" class="form-control" required />
                        <p class="invalid-feedback">{% trans 'requested_parts_required' %} </p>
                    </div>
                    <div class="form-group my-2">
                        <label for="" class="text-primary">{% trans 'details' %}</label>
                        <textarea name="details" class="form-control" id="" cols="30" rows="2"></textarea>
                    </div>
                    <div class="form-group my-2">
                        <label for="" class="text-primary"> {% trans 'files' %}</label>
                        <input type="file" name="file" multiple id="" class="form-control">
                    </div>
                    <input type="submit" value="{% trans 'save' %}" class="btn btn-info w-100">
                </form>
            </div>
        </div>
    </div>
</div>

templates/service/modals/sp_modal.html
<div class="modal fade" id="sp_modal" tabindex="-1" role="dialog" >
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">تفاصيل طلب قطع غيار </h4>
            </div>
            <div class="modal-body">
                <ul class="list-group " id="sp_details">
                    

                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>

            </div>
        </div>
    </div>
</div>



{% load static %} 
{% block script %}
<script src="{% static 'asset/libs/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap tether Core JavaScript -->
<script src="{% static 'asset/libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
<script>
    $(document).ready(function(){
        var modalShown = false;

        $('#sp_modal').on('show.bs.modal', function (event) {
            
            if (!modalShown) {
                modalShown = true
            event.stopPropagation()
            var button = $(event.relatedTarget);
            var id = button.data('id');
            var modal = $(this);

            $.ajax({
                url: '/api/sp_request/' + id,
                method: 'GET',
                success: function (data) {
                    let service_date = data.service.created_at
                    let service_date_obj = new Date(service_date);
                    let company_username = data.service.company ? data.service.company.username : "";
                    $('#sp_details').append(`
                        <li class="list-group-item">طلب الصيانة : <span id="repair_service"><a href='/service/${data.service.id}/details'>${data.service.ref_number}</a></span></li>
                    <li class="list-group-item">تاريخ طلب الصيانة: <span id="repair_service_date">${service_date_obj.toLocaleString()}</span></li>
                    <li class="list-group-item">طلب الصيانة بواسطة : <span id="repair_service_by">${data.service.created_by.username}</span></li>
                    <li class="list-group-item">الشركة: <span id="company">${company_username}</span></li>
                    <li class="list-group-item"> القطع المطلوبة : <span id="requested_parts">${data.requested_parts}</span></li>
                    <li class="list-group-item"> التفاصيل: <span id="requested_parts_details">${data.details}</span></li>
                    <li class="list-group-item"> حالة الطلب :  <span id="status"></span></li>`
                    )
                    let statusEl = modal.find('#status')
                    if (data.status == 'recieved') {
                        statusEl.addClass('text-success')
                        statusEl.text('تم الاستلام')
                        let recieve_date = data.recievied_at
                        var recieve_date_obj = new Date(recieve_date);
                        $('#sp_details').append(
                            `
                            <li class='list-group-item'> تاريخ الاستلام : ${recieve_date}</li>  
                            <li class='list-group-item'> المستلم: ${data.recievied_by.username} </li>  
                            `

                        )

                    } else {
                        statusEl.addClass('text-warning')
                        statusEl.text('لم يتم الاستلام ')
                    }
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.log(errorThrown);
                }
            });
        }
        });
        $('#sp_modal').on('hidden.bs.modal', function (event) {
            // clear the data in the modal
            $('#sp_details').empty();
            modalShown = false;
        });
    })

</script>
{% endblock %}